### ISSUE TITLE
Add widget(s)

### ISSUE THREAD

**Issue by Stradvr** [Akylas/oss-weather#120] opened 2024-03-03 18:19 UTC
This is arguably the most important feature in a weather app, atleast for me.
The Rain app just has a standard one in the oreo style, which I really like:
![Screenshot_20240303-191555_Niagara Launcher~2](https://github.com/Akylas/oss-weather/assets/50593360/88408e80-5219-46ed-b76b-fe6d77c938fe)

**Comment by farfromrefug** [comment] 2024-03-03 20:16
@Stradvr I ll think about it but dont know when yet. Will close this issue to prevent too many duplicate issues
duplicate of https://github.com/Akylas/oss-weather/issues/37

**Closed by farfromrefug** 2024-03-03 20:16 UTC
